// =============================================================================
// REPORT EXPORT SERVICE
// Enhanced export functionality with Documents folder saving capability
// =============================================================================

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

export interface ExportOptions {
  filename?: string;
  saveLocation?: 'downloads' | 'documents' | 'custom';
  customPath?: string;
  format: 'pdf' | 'excel' | 'csv';
  includeCharts?: boolean;
  includeMetadata?: boolean;
}

export interface ReportData {
  title: string;
  subtitle?: string;
  period: string;
  organization: string;
  generatedDate: string;
  data: any[];
  summary?: Record<string, any>;
  metadata?: Record<string, any>;
}

export class ReportExportService {
  private static instance: ReportExportService;

  public static getInstance(): ReportExportService {
    if (!ReportExportService.instance) {
      ReportExportService.instance = new ReportExportService();
    }
    return ReportExportService.instance;
  }

  /**
   * Export report with enhanced saving options
   */
  public async exportReport(reportData: ReportData, options: ExportOptions): Promise<void> {
    const filename = this.generateFilename(reportData, options);

    try {
      switch (options.format) {
        case 'pdf':
          await this.exportToPDF(reportData, filename, options);
          break;
        case 'excel':
          await this.exportToExcel(reportData, filename, options);
          break;
        case 'csv':
          await this.exportToCSV(reportData, filename, options);
          break;
        default:
          throw new Error(`Unsupported export format: ${options.format}`);
      }

      // Show success notification
      this.showExportSuccess(filename, options.saveLocation || 'downloads');
    } catch (error) {
      console.error('Export failed:', error);
      this.showExportError(error as Error);
    }
  }

  /**
   * Export to PDF with professional formatting
   */
  private async exportToPDF(reportData: ReportData, filename: string, options: ExportOptions): Promise<void> {
    const doc = new jsPDF('p', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Header
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text(reportData.title, pageWidth / 2, 20, { align: 'center' });

    if (reportData.subtitle) {
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text(reportData.subtitle, pageWidth / 2, 30, { align: 'center' });
    }

    // Organization and period info
    doc.setFontSize(12);
    doc.text(`Organization: ${reportData.organization}`, 20, 45);
    doc.text(`Period: ${reportData.period}`, 20, 52);
    doc.text(`Generated: ${reportData.generatedDate}`, 20, 59);

    // Data table
    if (reportData.data && reportData.data.length > 0) {
      const tableColumns = Object.keys(reportData.data[0]);
      const tableData = reportData.data.map(row => tableColumns.map(col => row[col]));

      autoTable(doc, {
        head: [tableColumns],
        body: tableData,
        startY: 70,
        theme: 'grid',
        styles: {
          fontSize: 10,
          cellPadding: 3,
        },
        headStyles: {
          fillColor: [41, 128, 185],
          textColor: 255,
          fontStyle: 'bold',
        },
        alternateRowStyles: {
          fillColor: [245, 245, 245],
        },
      });
    }

    // Summary section
    if (reportData.summary) {
      const finalY = (doc as any).lastAutoTable?.finalY || 150;
      doc.setFontSize(14);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 20, finalY + 20);

      doc.setFontSize(11);
      doc.setFont('helvetica', 'normal');
      let yPos = finalY + 30;

      Object.entries(reportData.summary).forEach(([key, value]) => {
        doc.text(`${key}: ${value}`, 20, yPos);
        yPos += 7;
      });
    }

    // Footer
    const totalPages = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(
        `Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
      doc.text(
        `Generated by StockFlow Financial Reporting System`,
        pageWidth / 2,
        pageHeight - 5,
        { align: 'center' }
      );
    }

    await this.saveFile(doc.output('blob'), filename, options);
  }

  /**
   * Export to Excel with multiple sheets and formatting
   */
  private async exportToExcel(reportData: ReportData, filename: string, options: ExportOptions): Promise<void> {
    const workbook = XLSX.utils.book_new();

    // Main data sheet
    if (reportData.data && reportData.data.length > 0) {
      const worksheet = XLSX.utils.json_to_sheet(reportData.data);

      // Add formatting
      const range = XLSX.utils.decode_range(worksheet['!ref'] || 'A1');

      // Header formatting
      for (let col = range.s.c; col <= range.e.c; col++) {
        const cellAddress = XLSX.utils.encode_cell({ r: 0, c: col });
        if (worksheet[cellAddress]) {
          worksheet[cellAddress].s = {
            font: { bold: true, color: { rgb: "FFFFFF" } },
            fill: { fgColor: { rgb: "2980B9" } },
            alignment: { horizontal: "center" }
          };
        }
      }

      XLSX.utils.book_append_sheet(workbook, worksheet, 'Report Data');
    }

    // Summary sheet
    if (reportData.summary) {
      const summaryData = Object.entries(reportData.summary).map(([key, value]) => ({
        Metric: key,
        Value: value
      }));
      const summarySheet = XLSX.utils.json_to_sheet(summaryData);
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary');
    }

    // Metadata sheet
    if (options.includeMetadata && reportData.metadata) {
      const metadataData = [
        { Field: 'Title', Value: reportData.title },
        { Field: 'Period', Value: reportData.period },
        { Field: 'Organization', Value: reportData.organization },
        { Field: 'Generated Date', Value: reportData.generatedDate },
        ...Object.entries(reportData.metadata).map(([key, value]) => ({
          Field: key,
          Value: value
        }))
      ];
      const metadataSheet = XLSX.utils.json_to_sheet(metadataData);
      XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata');
    }

    const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
    const blob = new Blob([excelBuffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    });

    await this.saveFile(blob, filename, options);
  }

  /**
   * Export to CSV format
   */
  private async exportToCSV(reportData: ReportData, filename: string, options: ExportOptions): Promise<void> {
    if (!reportData.data || reportData.data.length === 0) {
      throw new Error('No data available for CSV export');
    }

    const headers = Object.keys(reportData.data[0]);
    const csvContent = [
      // Header row
      headers.join(','),
      // Data rows
      ...reportData.data.map(row =>
        headers.map(header => {
          const value = row[header];
          // Escape commas and quotes in CSV
          if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
            return `"${value.replace(/"/g, '""')}"`;
          }
          return value;
        }).join(',')
      )
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    await this.saveFile(blob, filename, options);
  }

  /**
   * Save file to specified location
   */
  private async saveFile(blob: Blob, filename: string, options: ExportOptions): Promise<void> {
    if (typeof window !== 'undefined') {
      // Browser environment
      if (options.saveLocation === 'documents' && 'showDirectoryPicker' in window) {
        try {
          // Use File System Access API for Documents folder (Chrome/Edge)
          await this.saveToDocumentsFolder(blob, filename);
          return;
        } catch (error) {
          console.warn('Could not save to Documents folder, falling back to downloads:', error);
        }
      }

      // Fallback to download
      this.downloadFile(blob, filename);
    } else {
      // Node.js environment - save to file system
      await this.saveToFileSystem(blob, filename, options);
    }
  }

  /**
   * Save to Documents folder using File System Access API
   */
  private async saveToDocumentsFolder(blob: Blob, filename: string): Promise<void> {
    if (!('showDirectoryPicker' in window)) {
      throw new Error('File System Access API not supported');
    }

    try {
      // Request access to Documents folder
      const directoryHandle = await (window as any).showDirectoryPicker({
        suggestedName: 'Documents',
        mode: 'readwrite'
      });

      // Create the file
      const fileHandle = await directoryHandle.getFileHandle(filename, {
        create: true
      });

      // Write the blob
      const writable = await fileHandle.createWritable();
      await writable.write(blob);
      await writable.close();

      console.log(`File saved to Documents folder: ${filename}`);
    } catch (error) {
      if ((error as any).name === 'AbortError') {
        throw new Error('User cancelled file save operation');
      }
      throw error;
    }
  }

  /**
   * Traditional download method
   */
  private downloadFile(blob: Blob, filename: string): void {
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  /**
   * Save to file system (Node.js environment)
   */
  private async saveToFileSystem(blob: Blob, filename: string, options: ExportOptions): Promise<void> {
    // This would be implemented for server-side environments
    // using Node.js fs module
    console.log(`Server-side file saving not implemented: ${filename}`);
  }

  /**
   * Generate appropriate filename
   */
  private generateFilename(reportData: ReportData, options: ExportOptions): string {
    if (options.filename) {
      return this.ensureExtension(options.filename, options.format);
    }

    const safeName = reportData.title
      .replace(/[^a-zA-Z0-9\s-]/g, '')
      .replace(/\s+/g, '_')
      .toLowerCase();

    const timestamp = new Date().toISOString().split('T')[0];
    const extension = this.getFileExtension(options.format);

    return `${safeName}_${reportData.period}_${timestamp}.${extension}`;
  }

  /**
   * Ensure filename has correct extension
   */
  private ensureExtension(filename: string, format: string): string {
    const extension = this.getFileExtension(format);
    if (!filename.toLowerCase().endsWith(`.${extension}`)) {
      return `${filename}.${extension}`;
    }
    return filename;
  }

  /**
   * Get file extension for format
   */
  private getFileExtension(format: string): string {
    switch (format) {
      case 'pdf': return 'pdf';
      case 'excel': return 'xlsx';
      case 'csv': return 'csv';
      default: return 'txt';
    }
  }

  /**
   * Show export success notification
   */
  private showExportSuccess(filename: string, location: string): void {
    // This would integrate with your notification system
    console.log(`Export successful: ${filename} saved to ${location}`);

    // You could integrate with your existing notification system here
    // For example:
    // useNotifications().success('Export Successful', `Report saved as ${filename}`);
  }

  /**
   * Show export error notification
   */
  private showExportError(error: Error): void {
    // This would integrate with your notification system
    console.error('Export failed:', error);

    // You could integrate with your existing notification system here
    // For example:
    // useNotifications().error('Export Failed', error.message);
  }
}

// =============================================================================
// EXPORT UTILITIES
// =============================================================================

/**
 * Quick export functions for common use cases
 */
export const exportUtils = {
  /**
   * Export financial statement to Documents folder
   */
  async exportFinancialStatement(
    statementData: any[],
    title: string,
    period: string,
    format: 'pdf' | 'excel' | 'csv' = 'pdf'
  ): Promise<void> {
    const reportData: ReportData = {
      title,
      period,
      organization: 'StockFlow Enterprise',
      generatedDate: new Date().toLocaleString(),
      data: statementData
    };

    const options: ExportOptions = {
      format,
      saveLocation: 'documents',
      includeMetadata: true
    };

    await ReportExportService.getInstance().exportReport(reportData, options);
  },

  /**
   * Export budget report with variance analysis
   */
  async exportBudgetReport(
    budgetData: any[],
    budgetName: string,
    period: string,
    summary: Record<string, any>
  ): Promise<void> {
    const reportData: ReportData = {
      title: `Budget Report - ${budgetName}`,
      period,
      organization: 'StockFlow Enterprise',
      generatedDate: new Date().toLocaleString(),
      data: budgetData,
      summary
    };

    const options: ExportOptions = {
      format: 'excel',
      saveLocation: 'documents',
      includeMetadata: true,
      includeCharts: true
    };

    await ReportExportService.getInstance().exportReport(reportData, options);
  },

  /**
   * Export general ledger to Documents folder
   */
  async exportGeneralLedger(
    ledgerData: any[],
    accountName: string,
    period: string
  ): Promise<void> {
    const reportData: ReportData = {
      title: `General Ledger - ${accountName}`,
      period,
      organization: 'StockFlow Enterprise',
      generatedDate: new Date().toLocaleString(),
      data: ledgerData
    };

    const options: ExportOptions = {
      format: 'excel',
      saveLocation: 'documents'
    };

    await ReportExportService.getInstance().exportReport(reportData, options);
  }
};

export default ReportExportService;