// =============================================================================
// FINANCIAL REPORTING PERMISSIONS - Enterprise Grade Security
// =============================================================================

export const FINANCIAL_PERMISSIONS = {
  // =============================================================================
  // FINANCIAL STATEMENTS & REPORTS
  // =============================================================================

  // Financial Statements Access
  VIEW_INCOME_STATEMENT: 'VIEW_INCOME_STATEMENT',
  VIEW_BALANCE_SHEET: 'VIEW_BALANCE_SHEET',
  VIEW_CASH_FLOW_STATEMENT: 'VIEW_CASH_FLOW_STATEMENT',
  VIEW_COMPREHENSIVE_FINANCIAL_REPORTS: 'VIEW_COMPREHENSIVE_FINANCIAL_REPORTS',

  // Financial Statements Management
  GENERATE_FINANCIAL_STATEMENTS: 'GENERATE_FINANCIAL_STATEMENTS',
  APPROVE_FINANCIAL_STATEMENTS: 'APPROVE_FINANCIAL_STATEMENTS',
  PUBLISH_FINANCIAL_STATEMENTS: 'PUBLISH_FINANCIAL_STATEMENTS',
  ARCHIVE_FINANCIAL_STATEMENTS: 'ARCHIVE_FINANCIAL_STATEMENTS',

  // Export & Distribution
  EXPORT_FINANCIAL_REPORTS: 'EXPORT_FINANCIAL_REPORTS',
  DISTRIBUTE_FINANCIAL_REPORTS: 'DISTRIBUTE_FINANCIAL_REPORTS',
  EMAIL_FINANCIAL_REPORTS: 'EMAIL_FINANCIAL_REPORTS',

  // =============================================================================
  // CHART OF ACCOUNTS & GENERAL LEDGER
  // =============================================================================

  // Chart of Accounts
  VIEW_CHART_OF_ACCOUNTS: 'VIEW_CHART_OF_ACCOUNTS',
  CREATE_ACCOUNTS: 'CREATE_ACCOUNTS',
  UPDATE_ACCOUNTS: 'UPDATE_ACCOUNTS',
  DELETE_ACCOUNTS: 'DELETE_ACCOUNTS',
  MANAGE_ACCOUNT_HIERARCHY: 'MANAGE_ACCOUNT_HIERARCHY',
  CONFIGURE_TAX_REPORTING: 'CONFIGURE_TAX_REPORTING',

  // General Ledger
  VIEW_GENERAL_LEDGER: 'VIEW_GENERAL_LEDGER',
  VIEW_TRIAL_BALANCE: 'VIEW_TRIAL_BALANCE',
  VIEW_ACCOUNT_BALANCES: 'VIEW_ACCOUNT_BALANCES',
  VIEW_ACCOUNT_HISTORY: 'VIEW_ACCOUNT_HISTORY',

  // =============================================================================
  // JOURNAL ENTRIES & TRANSACTIONS
  // =============================================================================

  // Journal Entry Management
  CREATE_JOURNAL_ENTRIES: 'CREATE_JOURNAL_ENTRIES',
  VIEW_JOURNAL_ENTRIES: 'VIEW_JOURNAL_ENTRIES',
  UPDATE_JOURNAL_ENTRIES: 'UPDATE_JOURNAL_ENTRIES',
  DELETE_JOURNAL_ENTRIES: 'DELETE_JOURNAL_ENTRIES',

  // Journal Entry Workflow
  SUBMIT_JOURNAL_ENTRIES: 'SUBMIT_JOURNAL_ENTRIES',
  APPROVE_JOURNAL_ENTRIES: 'APPROVE_JOURNAL_ENTRIES',
  REJECT_JOURNAL_ENTRIES: 'REJECT_JOURNAL_ENTRIES',
  POST_JOURNAL_ENTRIES: 'POST_JOURNAL_ENTRIES',
  REVERSE_JOURNAL_ENTRIES: 'REVERSE_JOURNAL_ENTRIES',

  // Manual Adjustments
  CREATE_MANUAL_ADJUSTMENTS: 'CREATE_MANUAL_ADJUSTMENTS',
  APPROVE_MANUAL_ADJUSTMENTS: 'APPROVE_MANUAL_ADJUSTMENTS',
  POST_ADJUSTING_ENTRIES: 'POST_ADJUSTING_ENTRIES',

  // =============================================================================
  // FINANCIAL ANALYSIS & RATIOS
  // =============================================================================

  // Financial Analysis
  VIEW_FINANCIAL_RATIOS: 'VIEW_FINANCIAL_RATIOS',
  VIEW_FINANCIAL_TRENDS: 'VIEW_FINANCIAL_TRENDS',
  VIEW_DUPONT_ANALYSIS: 'VIEW_DUPONT_ANALYSIS',
  VIEW_COMMON_SIZE_ANALYSIS: 'VIEW_COMMON_SIZE_ANALYSIS',

  // Advanced Analytics
  VIEW_SCENARIO_ANALYSIS: 'VIEW_SCENARIO_ANALYSIS',
  CREATE_FINANCIAL_SCENARIOS: 'CREATE_FINANCIAL_SCENARIOS',
  VIEW_FINANCIAL_FORECASTS: 'VIEW_FINANCIAL_FORECASTS',
  GENERATE_FINANCIAL_FORECASTS: 'GENERATE_FINANCIAL_FORECASTS',

  // Industry Benchmarking
  VIEW_INDUSTRY_BENCHMARKS: 'VIEW_INDUSTRY_BENCHMARKS',
  CONFIGURE_BENCHMARK_SETTINGS: 'CONFIGURE_BENCHMARK_SETTINGS',

  // =============================================================================
  // BUDGETS & VARIANCE ANALYSIS
  // =============================================================================

  // Budget Management
  VIEW_BUDGETS: 'VIEW_BUDGETS',
  CREATE_BUDGETS: 'CREATE_BUDGETS',
  UPDATE_BUDGETS: 'UPDATE_BUDGETS',
  DELETE_BUDGETS: 'DELETE_BUDGETS',

  // Budget Workflow
  SUBMIT_BUDGETS: 'SUBMIT_BUDGETS',
  APPROVE_BUDGETS: 'APPROVE_BUDGETS',
  REJECT_BUDGETS: 'REJECT_BUDGETS',
  ACTIVATE_BUDGETS: 'ACTIVATE_BUDGETS',

  // Variance Analysis
  VIEW_BUDGET_VARIANCE: 'VIEW_BUDGET_VARIANCE',
  VIEW_VARIANCE_REPORTS: 'VIEW_VARIANCE_REPORTS',
  INVESTIGATE_VARIANCES: 'INVESTIGATE_VARIANCES',

  // =============================================================================
  // FINANCIAL CONTROLS & COMPLIANCE
  // =============================================================================

  // Internal Controls
  VIEW_FINANCIAL_CONTROLS: 'VIEW_FINANCIAL_CONTROLS',
  MANAGE_FINANCIAL_CONTROLS: 'MANAGE_FINANCIAL_CONTROLS',
  TEST_FINANCIAL_CONTROLS: 'TEST_FINANCIAL_CONTROLS',
  DOCUMENT_CONTROL_TESTING: 'DOCUMENT_CONTROL_TESTING',

  // Compliance Management
  VIEW_COMPLIANCE_STATUS: 'VIEW_COMPLIANCE_STATUS',
  MANAGE_COMPLIANCE_REQUIREMENTS: 'MANAGE_COMPLIANCE_REQUIREMENTS',
  GENERATE_COMPLIANCE_REPORTS: 'GENERATE_COMPLIANCE_REPORTS',
  CERTIFY_COMPLIANCE: 'CERTIFY_COMPLIANCE',

  // SOX Compliance
  MANAGE_SOX_CONTROLS: 'MANAGE_SOX_CONTROLS',
  PERFORM_SOX_TESTING: 'PERFORM_SOX_TESTING',
  DOCUMENT_SOX_DEFICIENCIES: 'DOCUMENT_SOX_DEFICIENCIES',
  REMEDIATE_SOX_DEFICIENCIES: 'REMEDIATE_SOX_DEFICIENCIES',

  // =============================================================================
  // AUDIT TRAIL & SECURITY
  // =============================================================================

  // Audit Trail
  VIEW_FINANCIAL_AUDIT_TRAIL: 'VIEW_FINANCIAL_AUDIT_TRAIL',
  VIEW_TRANSACTION_HISTORY: 'VIEW_TRANSACTION_HISTORY',
  INVESTIGATE_AUDIT_FINDINGS: 'INVESTIGATE_AUDIT_FINDINGS',
  EXPORT_AUDIT_LOGS: 'EXPORT_AUDIT_LOGS',

  // Security & Access Control
  MANAGE_FINANCIAL_USER_ACCESS: 'MANAGE_FINANCIAL_USER_ACCESS',
  GRANT_FINANCIAL_PERMISSIONS: 'GRANT_FINANCIAL_PERMISSIONS',
  REVOKE_FINANCIAL_PERMISSIONS: 'REVOKE_FINANCIAL_PERMISSIONS',
  MONITOR_FINANCIAL_ACCESS: 'MONITOR_FINANCIAL_ACCESS',

  // Data Security
  ENCRYPT_FINANCIAL_DATA: 'ENCRYPT_FINANCIAL_DATA',
  BACKUP_FINANCIAL_DATA: 'BACKUP_FINANCIAL_DATA',
  RESTORE_FINANCIAL_DATA: 'RESTORE_FINANCIAL_DATA',
  PURGE_FINANCIAL_DATA: 'PURGE_FINANCIAL_DATA',

  // =============================================================================
  // RISK MANAGEMENT & ASSESSMENT
  // =============================================================================

  // Financial Risk Assessment
  VIEW_FINANCIAL_RISKS: 'VIEW_FINANCIAL_RISKS',
  ASSESS_FINANCIAL_RISKS: 'ASSESS_FINANCIAL_RISKS',
  MANAGE_RISK_MITIGATION: 'MANAGE_RISK_MITIGATION',
  MONITOR_RISK_INDICATORS: 'MONITOR_RISK_INDICATORS',

  // Credit Risk Management
  VIEW_CREDIT_ANALYSIS: 'VIEW_CREDIT_ANALYSIS',
  PERFORM_CREDIT_ASSESSMENTS: 'PERFORM_CREDIT_ASSESSMENTS',
  SET_CREDIT_LIMITS: 'SET_CREDIT_LIMITS',
  MONITOR_CREDIT_EXPOSURE: 'MONITOR_CREDIT_EXPOSURE',

  // Fraud Detection
  VIEW_FRAUD_ALERTS: 'VIEW_FRAUD_ALERTS',
  INVESTIGATE_FRAUD_CASES: 'INVESTIGATE_FRAUD_CASES',
  REPORT_FRAUD_INCIDENTS: 'REPORT_FRAUD_INCIDENTS',
  IMPLEMENT_FRAUD_CONTROLS: 'IMPLEMENT_FRAUD_CONTROLS',

  // =============================================================================
  // PERIOD MANAGEMENT & CLOSE
  // =============================================================================

  // Financial Periods
  VIEW_FINANCIAL_PERIODS: 'VIEW_FINANCIAL_PERIODS',
  CREATE_FINANCIAL_PERIODS: 'CREATE_FINANCIAL_PERIODS',
  MANAGE_PERIOD_STATUS: 'MANAGE_PERIOD_STATUS',
  CLOSE_FINANCIAL_PERIODS: 'CLOSE_FINANCIAL_PERIODS',
  REOPEN_FINANCIAL_PERIODS: 'REOPEN_FINANCIAL_PERIODS',

  // Month-End Close
  INITIATE_MONTH_END_CLOSE: 'INITIATE_MONTH_END_CLOSE',
  PERFORM_MONTH_END_PROCEDURES: 'PERFORM_MONTH_END_PROCEDURES',
  REVIEW_MONTH_END_ADJUSTMENTS: 'REVIEW_MONTH_END_ADJUSTMENTS',
  APPROVE_MONTH_END_CLOSE: 'APPROVE_MONTH_END_CLOSE',

  // Year-End Close
  INITIATE_YEAR_END_CLOSE: 'INITIATE_YEAR_END_CLOSE',
  PERFORM_YEAR_END_PROCEDURES: 'PERFORM_YEAR_END_PROCEDURES',
  APPROVE_YEAR_END_CLOSE: 'APPROVE_YEAR_END_CLOSE',

  // =============================================================================
  // TAX MANAGEMENT
  // =============================================================================

  // Tax Calculations
  VIEW_TAX_CALCULATIONS: 'VIEW_TAX_CALCULATIONS',
  CALCULATE_TAX_LIABILITY: 'CALCULATE_TAX_LIABILITY',
  ADJUST_TAX_CALCULATIONS: 'ADJUST_TAX_CALCULATIONS',
  APPROVE_TAX_CALCULATIONS: 'APPROVE_TAX_CALCULATIONS',

  // Tax Reporting
  GENERATE_TAX_REPORTS: 'GENERATE_TAX_REPORTS',
  FILE_TAX_RETURNS: 'FILE_TAX_RETURNS',
  RESPOND_TO_TAX_INQUIRIES: 'RESPOND_TO_TAX_INQUIRIES',
  MANAGE_TAX_DOCUMENTATION: 'MANAGE_TAX_DOCUMENTATION',

  // =============================================================================
  // TREASURY & CASH MANAGEMENT
  // =============================================================================

  // Cash Management
  VIEW_CASH_POSITIONS: 'VIEW_CASH_POSITIONS',
  MANAGE_CASH_FLOW_FORECASTS: 'MANAGE_CASH_FLOW_FORECASTS',
  AUTHORIZE_CASH_TRANSFERS: 'AUTHORIZE_CASH_TRANSFERS',
  RECONCILE_BANK_ACCOUNTS: 'RECONCILE_BANK_ACCOUNTS',

  // Investment Management
  VIEW_INVESTMENT_PORTFOLIOS: 'VIEW_INVESTMENT_PORTFOLIOS',
  AUTHORIZE_INVESTMENTS: 'AUTHORIZE_INVESTMENTS',
  MONITOR_INVESTMENT_PERFORMANCE: 'MONITOR_INVESTMENT_PERFORMANCE',
  REPORT_INVESTMENT_RETURNS: 'REPORT_INVESTMENT_RETURNS',

  // Debt Management
  VIEW_DEBT_POSITIONS: 'VIEW_DEBT_POSITIONS',
  MANAGE_DEBT_AGREEMENTS: 'MANAGE_DEBT_AGREEMENTS',
  MONITOR_DEBT_COVENANTS: 'MONITOR_DEBT_COVENANTS',
  REPORT_DEBT_COMPLIANCE: 'REPORT_DEBT_COMPLIANCE',

  // =============================================================================
  // SYSTEM ADMINISTRATION
  // =============================================================================

  // Financial System Config
  CONFIGURE_FINANCIAL_SYSTEM: 'CONFIGURE_FINANCIAL_SYSTEM',
  MANAGE_FINANCIAL_INTEGRATIONS: 'MANAGE_FINANCIAL_INTEGRATIONS',
  CONFIGURE_FINANCIAL_WORKFLOWS: 'CONFIGURE_FINANCIAL_WORKFLOWS',
  MANAGE_FINANCIAL_NOTIFICATIONS: 'MANAGE_FINANCIAL_NOTIFICATIONS',

  // Data Management
  IMPORT_FINANCIAL_DATA: 'IMPORT_FINANCIAL_DATA',
  EXPORT_FINANCIAL_DATA: 'EXPORT_FINANCIAL_DATA',
  MIGRATE_FINANCIAL_DATA: 'MIGRATE_FINANCIAL_DATA',
  ARCHIVE_FINANCIAL_DATA: 'ARCHIVE_FINANCIAL_DATA',

  // System Monitoring
  MONITOR_FINANCIAL_SYSTEM_HEALTH: 'MONITOR_FINANCIAL_SYSTEM_HEALTH',
  VIEW_FINANCIAL_SYSTEM_LOGS: 'VIEW_FINANCIAL_SYSTEM_LOGS',
  TROUBLESHOOT_FINANCIAL_ISSUES: 'TROUBLESHOOT_FINANCIAL_ISSUES',
  OPTIMIZE_FINANCIAL_PERFORMANCE: 'OPTIMIZE_FINANCIAL_PERFORMANCE',
} as const;

// =============================================================================
// FINANCIAL ROLE TEMPLATES WITH GRANULAR PERMISSIONS
// =============================================================================

export const FINANCIAL_ROLE_TEMPLATES = {
  // =============================================================================
  // C-LEVEL & EXECUTIVE ROLES
  // =============================================================================

  CHIEF_FINANCIAL_OFFICER: {
    name: 'Chief Financial Officer',
    code: 'cfo',
    description: 'Chief Financial Officer with full financial system access',
    category: 'EXECUTIVE',
    hierarchy: 1,
    permissions: [
      // Full access to all financial permissions
      ...Object.values(FINANCIAL_PERMISSIONS),
    ],
    riskLevel: 'CRITICAL',
    requiresApproval: true,
    maxUsers: 1,
  },

  CHIEF_EXECUTIVE_OFFICER: {
    name: 'Chief Executive Officer',
    code: 'ceo',
    description: 'Chief Executive Officer with strategic financial oversight',
    category: 'EXECUTIVE',
    hierarchy: 1,
    permissions: [
      // Financial Overview & Strategic
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_SCENARIO_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.VIEW_INDUSTRY_BENCHMARKS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.APPROVE_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_VARIANCE_REPORTS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.APPROVE_FINANCIAL_STATEMENTS,
      FINANCIAL_PERMISSIONS.CERTIFY_COMPLIANCE,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.DISTRIBUTE_FINANCIAL_REPORTS,
    ],
    riskLevel: 'CRITICAL',
    requiresApproval: false,
    maxUsers: 1,
  },

  // =============================================================================
  // SENIOR MANAGEMENT ROLES
  // =============================================================================

  FINANCIAL_CONTROLLER: {
    name: 'Financial Controller',
    code: 'controller',
    description: 'Financial Controller with comprehensive financial management access',
    category: 'SENIOR_MANAGEMENT',
    hierarchy: 2,
    permissions: [
      // Financial Statements
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_STATEMENTS,
      FINANCIAL_PERMISSIONS.APPROVE_FINANCIAL_STATEMENTS,

      // Chart of Accounts & GL
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.CREATE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.UPDATE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.MANAGE_ACCOUNT_HIERARCHY,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,

      // Journal Entries
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.APPROVE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.POST_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.REVERSE_JOURNAL_ENTRIES,

      // Analysis & Reporting
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_DUPONT_ANALYSIS,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,

      // Budget Management
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.CREATE_BUDGETS,
      FINANCIAL_PERMISSIONS.UPDATE_BUDGETS,
      FINANCIAL_PERMISSIONS.APPROVE_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,

      // Controls & Compliance
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.MANAGE_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.VIEW_COMPLIANCE_STATUS,

      // Period Management
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_PERIODS,
      FINANCIAL_PERMISSIONS.MANAGE_PERIOD_STATUS,
      FINANCIAL_PERMISSIONS.INITIATE_MONTH_END_CLOSE,
      FINANCIAL_PERMISSIONS.APPROVE_MONTH_END_CLOSE,

      // Audit & Security
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      FINANCIAL_PERMISSIONS.INVESTIGATE_AUDIT_FINDINGS,
    ],
    riskLevel: 'HIGH',
    requiresApproval: true,
    maxUsers: 2,
  },

  ASSISTANT_CONTROLLER: {
    name: 'Assistant Controller',
    code: 'assistant_controller',
    description: 'Assistant Controller with operational financial access',
    category: 'MANAGEMENT',
    hierarchy: 3,
    permissions: [
      // Financial Statements (View Only)
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_STATEMENTS,

      // Chart of Accounts & GL
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.UPDATE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,

      // Journal Entries
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.SUBMIT_JOURNAL_ENTRIES,

      // Analysis
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,

      // Budget Support
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.CREATE_BUDGETS,
      FINANCIAL_PERMISSIONS.UPDATE_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,

      // Period Management
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_PERIODS,
      FINANCIAL_PERMISSIONS.PERFORM_MONTH_END_PROCEDURES,

      // Audit Trail
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,
    ],
    riskLevel: 'MEDIUM',
    requiresApproval: true,
    maxUsers: 3,
  },

  // =============================================================================
  // SPECIALIST ROLES
  // =============================================================================

  FINANCIAL_ANALYST: {
    name: 'Financial Analyst',
    code: 'financial_analyst',
    description: 'Financial Analyst with analysis and reporting focus',
    category: 'SPECIALIST',
    hierarchy: 4,
    permissions: [
      // Financial Statements (View Only)
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,

      // Analysis & Forecasting
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_DUPONT_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_COMMON_SIZE_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_SCENARIO_ANALYSIS,
      FINANCIAL_PERMISSIONS.CREATE_FINANCIAL_SCENARIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.VIEW_INDUSTRY_BENCHMARKS,

      // Budget Analysis
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,
      FINANCIAL_PERMISSIONS.VIEW_VARIANCE_REPORTS,
      FINANCIAL_PERMISSIONS.INVESTIGATE_VARIANCES,

      // Risk Assessment
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.ASSESS_FINANCIAL_RISKS,

      // Reporting
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,

      // Read-Only Access
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 10,
  },

  BUDGET_MANAGER: {
    name: 'Budget Manager',
    code: 'budget_manager',
    description: 'Budget Manager with budget planning and analysis focus',
    category: 'SPECIALIST',
    hierarchy: 4,
    permissions: [
      // Budget Management
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.CREATE_BUDGETS,
      FINANCIAL_PERMISSIONS.UPDATE_BUDGETS,
      FINANCIAL_PERMISSIONS.SUBMIT_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,
      FINANCIAL_PERMISSIONS.VIEW_VARIANCE_REPORTS,
      FINANCIAL_PERMISSIONS.INVESTIGATE_VARIANCES,

      // Financial Analysis (Limited)
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_FORECASTS,

      // Reporting
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,

      // Read-Only Access
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_PERIODS,
    ],
    riskLevel: 'MEDIUM',
    requiresApproval: false,
    maxUsers: 5,
  },

  // =============================================================================
  // OPERATIONAL ROLES
  // =============================================================================

  ACCOUNTING_CLERK: {
    name: 'Accounting Clerk',
    code: 'accounting_clerk',
    description: 'Accounting Clerk with data entry and basic reporting access',
    category: 'OPERATIONAL',
    hierarchy: 5,
    permissions: [
      // Journal Entries (Limited)
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.SUBMIT_JOURNAL_ENTRIES,

      // Read-Only Access
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,
      FINANCIAL_PERMISSIONS.VIEW_ACCOUNT_BALANCES,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_PERIODS,

      // Basic Reporting
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,

      // Month-End Support
      FINANCIAL_PERMISSIONS.PERFORM_MONTH_END_PROCEDURES,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 20,
  },

  ACCOUNTS_PAYABLE_CLERK: {
    name: 'Accounts Payable Clerk',
    code: 'ap_clerk',
    description: 'Accounts Payable Clerk with AP-specific access',
    category: 'OPERATIONAL',
    hierarchy: 5,
    permissions: [
      // AP-Specific Journal Entries
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,

      // Read-Only Access
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_ACCOUNT_BALANCES,
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,

      // Cash Management (Limited)
      FINANCIAL_PERMISSIONS.RECONCILE_BANK_ACCOUNTS,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 10,
  },

  ACCOUNTS_RECEIVABLE_CLERK: {
    name: 'Accounts Receivable Clerk',
    code: 'ar_clerk',
    description: 'Accounts Receivable Clerk with AR-specific access',
    category: 'OPERATIONAL',
    hierarchy: 5,
    permissions: [
      // AR-Specific Journal Entries
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,

      // Credit Management
      FINANCIAL_PERMISSIONS.VIEW_CREDIT_ANALYSIS,
      FINANCIAL_PERMISSIONS.PERFORM_CREDIT_ASSESSMENTS,
      FINANCIAL_PERMISSIONS.MONITOR_CREDIT_EXPOSURE,

      // Read-Only Access
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_ACCOUNT_BALANCES,
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 10,
  },

  // =============================================================================
  // AUDIT & COMPLIANCE ROLES
  // =============================================================================

  INTERNAL_AUDITOR: {
    name: 'Internal Auditor',
    code: 'internal_auditor',
    description: 'Internal Auditor with comprehensive audit access',
    category: 'AUDIT_COMPLIANCE',
    hierarchy: 3,
    permissions: [
      // Full Read Access
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,

      // Audit Trail & Investigation
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,
      FINANCIAL_PERMISSIONS.INVESTIGATE_AUDIT_FINDINGS,
      FINANCIAL_PERMISSIONS.EXPORT_AUDIT_LOGS,

      // Controls Testing
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.TEST_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.DOCUMENT_CONTROL_TESTING,

      // Compliance
      FINANCIAL_PERMISSIONS.VIEW_COMPLIANCE_STATUS,
      FINANCIAL_PERMISSIONS.GENERATE_COMPLIANCE_REPORTS,

      // Risk Assessment
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.ASSESS_FINANCIAL_RISKS,

      // Fraud Detection
      FINANCIAL_PERMISSIONS.VIEW_FRAUD_ALERTS,
      FINANCIAL_PERMISSIONS.INVESTIGATE_FRAUD_CASES,
      FINANCIAL_PERMISSIONS.REPORT_FRAUD_INCIDENTS,

      // Export & Reporting
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_DATA,
    ],
    riskLevel: 'MEDIUM',
    requiresApproval: true,
    maxUsers: 5,
  },

  COMPLIANCE_OFFICER: {
    name: 'Compliance Officer',
    code: 'compliance_officer',
    description: 'Compliance Officer with regulatory compliance focus',
    category: 'AUDIT_COMPLIANCE',
    hierarchy: 3,
    permissions: [
      // Compliance Management
      FINANCIAL_PERMISSIONS.VIEW_COMPLIANCE_STATUS,
      FINANCIAL_PERMISSIONS.MANAGE_COMPLIANCE_REQUIREMENTS,
      FINANCIAL_PERMISSIONS.GENERATE_COMPLIANCE_REPORTS,

      // SOX Compliance
      FINANCIAL_PERMISSIONS.MANAGE_SOX_CONTROLS,
      FINANCIAL_PERMISSIONS.PERFORM_SOX_TESTING,
      FINANCIAL_PERMISSIONS.DOCUMENT_SOX_DEFICIENCIES,
      FINANCIAL_PERMISSIONS.REMEDIATE_SOX_DEFICIENCIES,

      // Controls
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.MANAGE_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.TEST_FINANCIAL_CONTROLS,

      // Risk Management
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.ASSESS_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.MANAGE_RISK_MITIGATION,

      // Audit Trail
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      FINANCIAL_PERMISSIONS.INVESTIGATE_AUDIT_FINDINGS,

      // Limited Financial Access
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,
    ],
    riskLevel: 'MEDIUM',
    requiresApproval: true,
    maxUsers: 3,
  },

  // =============================================================================
  // READ-ONLY & REPORTING ROLES
  // =============================================================================

  FINANCIAL_VIEWER: {
    name: 'Financial Viewer',
    code: 'financial_viewer',
    description: 'Read-only access to financial reports and statements',
    category: 'VIEWER',
    hierarchy: 6,
    permissions: [
      // Financial Statements (Read-Only)
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,

      // Basic Analysis (Read-Only)
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_INDUSTRY_BENCHMARKS,

      // Budget Viewing
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,

      // Export
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 50,
  },

  EXECUTIVE_VIEWER: {
    name: 'Executive Viewer',
    code: 'executive_viewer',
    description: 'Executive-level read-only access with strategic focus',
    category: 'EXECUTIVE_VIEWER',
    hierarchy: 2,
    permissions: [
      // Financial Statements
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,

      // Strategic Analysis
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_DUPONT_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_SCENARIO_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.VIEW_INDUSTRY_BENCHMARKS,

      // Budget & Variance
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,
      FINANCIAL_PERMISSIONS.VIEW_VARIANCE_REPORTS,

      // Risk Overview
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.VIEW_COMPLIANCE_STATUS,

      // Export & Distribution
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.DISTRIBUTE_FINANCIAL_REPORTS,
    ],
    riskLevel: 'LOW',
    requiresApproval: false,
    maxUsers: 20,
  },
} as const;

// =============================================================================
// PERMISSION GROUPS FOR EASIER MANAGEMENT
// =============================================================================

export const FINANCIAL_PERMISSION_GROUPS = {
  FINANCIAL_STATEMENTS: {
    name: 'Financial Statements',
    description: 'Access to core financial statements',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_INCOME_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_BALANCE_SHEET,
      FINANCIAL_PERMISSIONS.VIEW_CASH_FLOW_STATEMENT,
      FINANCIAL_PERMISSIONS.VIEW_COMPREHENSIVE_FINANCIAL_REPORTS,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_STATEMENTS,
      FINANCIAL_PERMISSIONS.APPROVE_FINANCIAL_STATEMENTS,
      FINANCIAL_PERMISSIONS.PUBLISH_FINANCIAL_STATEMENTS,
    ],
  },

  GENERAL_LEDGER: {
    name: 'General Ledger & Chart of Accounts',
    description: 'General ledger and chart of accounts management',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_CHART_OF_ACCOUNTS,
      FINANCIAL_PERMISSIONS.CREATE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.UPDATE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.DELETE_ACCOUNTS,
      FINANCIAL_PERMISSIONS.MANAGE_ACCOUNT_HIERARCHY,
      FINANCIAL_PERMISSIONS.VIEW_GENERAL_LEDGER,
      FINANCIAL_PERMISSIONS.VIEW_TRIAL_BALANCE,
      FINANCIAL_PERMISSIONS.VIEW_ACCOUNT_BALANCES,
    ],
  },

  JOURNAL_ENTRIES: {
    name: 'Journal Entries',
    description: 'Journal entry management and workflow',
    permissions: [
      FINANCIAL_PERMISSIONS.CREATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.VIEW_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.UPDATE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.DELETE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.SUBMIT_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.APPROVE_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.POST_JOURNAL_ENTRIES,
      FINANCIAL_PERMISSIONS.REVERSE_JOURNAL_ENTRIES,
    ],
  },

  FINANCIAL_ANALYSIS: {
    name: 'Financial Analysis',
    description: 'Financial analysis and reporting tools',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RATIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_TRENDS,
      FINANCIAL_PERMISSIONS.VIEW_DUPONT_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_COMMON_SIZE_ANALYSIS,
      FINANCIAL_PERMISSIONS.VIEW_SCENARIO_ANALYSIS,
      FINANCIAL_PERMISSIONS.CREATE_FINANCIAL_SCENARIOS,
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_FORECASTS,
      FINANCIAL_PERMISSIONS.GENERATE_FINANCIAL_FORECASTS,
    ],
  },

  BUDGET_MANAGEMENT: {
    name: 'Budget Management',
    description: 'Budget planning and variance analysis',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_BUDGETS,
      FINANCIAL_PERMISSIONS.CREATE_BUDGETS,
      FINANCIAL_PERMISSIONS.UPDATE_BUDGETS,
      FINANCIAL_PERMISSIONS.DELETE_BUDGETS,
      FINANCIAL_PERMISSIONS.SUBMIT_BUDGETS,
      FINANCIAL_PERMISSIONS.APPROVE_BUDGETS,
      FINANCIAL_PERMISSIONS.VIEW_BUDGET_VARIANCE,
      FINANCIAL_PERMISSIONS.INVESTIGATE_VARIANCES,
    ],
  },

  COMPLIANCE_CONTROLS: {
    name: 'Compliance & Controls',
    description: 'Internal controls and regulatory compliance',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.MANAGE_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.TEST_FINANCIAL_CONTROLS,
      FINANCIAL_PERMISSIONS.VIEW_COMPLIANCE_STATUS,
      FINANCIAL_PERMISSIONS.MANAGE_COMPLIANCE_REQUIREMENTS,
      FINANCIAL_PERMISSIONS.GENERATE_COMPLIANCE_REPORTS,
      FINANCIAL_PERMISSIONS.MANAGE_SOX_CONTROLS,
      FINANCIAL_PERMISSIONS.PERFORM_SOX_TESTING,
    ],
  },

  AUDIT_SECURITY: {
    name: 'Audit & Security',
    description: 'Audit trail and security management',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_AUDIT_TRAIL,
      FINANCIAL_PERMISSIONS.VIEW_TRANSACTION_HISTORY,
      FINANCIAL_PERMISSIONS.INVESTIGATE_AUDIT_FINDINGS,
      FINANCIAL_PERMISSIONS.EXPORT_AUDIT_LOGS,
      FINANCIAL_PERMISSIONS.MANAGE_FINANCIAL_USER_ACCESS,
      FINANCIAL_PERMISSIONS.MONITOR_FINANCIAL_ACCESS,
    ],
  },

  RISK_MANAGEMENT: {
    name: 'Risk Management',
    description: 'Financial risk assessment and management',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.ASSESS_FINANCIAL_RISKS,
      FINANCIAL_PERMISSIONS.MANAGE_RISK_MITIGATION,
      FINANCIAL_PERMISSIONS.MONITOR_RISK_INDICATORS,
      FINANCIAL_PERMISSIONS.VIEW_CREDIT_ANALYSIS,
      FINANCIAL_PERMISSIONS.PERFORM_CREDIT_ASSESSMENTS,
      FINANCIAL_PERMISSIONS.VIEW_FRAUD_ALERTS,
      FINANCIAL_PERMISSIONS.INVESTIGATE_FRAUD_CASES,
    ],
  },

  PERIOD_MANAGEMENT: {
    name: 'Period Management',
    description: 'Financial period and close management',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_FINANCIAL_PERIODS,
      FINANCIAL_PERMISSIONS.CREATE_FINANCIAL_PERIODS,
      FINANCIAL_PERMISSIONS.MANAGE_PERIOD_STATUS,
      FINANCIAL_PERMISSIONS.CLOSE_FINANCIAL_PERIODS,
      FINANCIAL_PERMISSIONS.INITIATE_MONTH_END_CLOSE,
      FINANCIAL_PERMISSIONS.PERFORM_MONTH_END_PROCEDURES,
      FINANCIAL_PERMISSIONS.APPROVE_MONTH_END_CLOSE,
    ],
  },

  TREASURY_CASH: {
    name: 'Treasury & Cash Management',
    description: 'Cash and treasury management functions',
    permissions: [
      FINANCIAL_PERMISSIONS.VIEW_CASH_POSITIONS,
      FINANCIAL_PERMISSIONS.MANAGE_CASH_FLOW_FORECASTS,
      FINANCIAL_PERMISSIONS.AUTHORIZE_CASH_TRANSFERS,
      FINANCIAL_PERMISSIONS.RECONCILE_BANK_ACCOUNTS,
      FINANCIAL_PERMISSIONS.VIEW_INVESTMENT_PORTFOLIOS,
      FINANCIAL_PERMISSIONS.AUTHORIZE_INVESTMENTS,
      FINANCIAL_PERMISSIONS.VIEW_DEBT_POSITIONS,
      FINANCIAL_PERMISSIONS.MANAGE_DEBT_AGREEMENTS,
    ],
  },

  SYSTEM_ADMIN: {
    name: 'System Administration',
    description: 'Financial system configuration and management',
    permissions: [
      FINANCIAL_PERMISSIONS.CONFIGURE_FINANCIAL_SYSTEM,
      FINANCIAL_PERMISSIONS.MANAGE_FINANCIAL_INTEGRATIONS,
      FINANCIAL_PERMISSIONS.CONFIGURE_FINANCIAL_WORKFLOWS,
      FINANCIAL_PERMISSIONS.IMPORT_FINANCIAL_DATA,
      FINANCIAL_PERMISSIONS.EXPORT_FINANCIAL_DATA,
      FINANCIAL_PERMISSIONS.MONITOR_FINANCIAL_SYSTEM_HEALTH,
      FINANCIAL_PERMISSIONS.TROUBLESHOOT_FINANCIAL_ISSUES,
    ],
  },
} as const;

export type FinancialPermission = keyof typeof FINANCIAL_PERMISSIONS;
export type FinancialRoleTemplate = keyof typeof FINANCIAL_ROLE_TEMPLATES;
export type FinancialPermissionGroup = keyof typeof FINANCIAL_PERMISSION_GROUPS;